FROM debian:12 AS builder

RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*
COPY main.c /app/main.c
RUN gcc -o /app/main /app/main.c


FROM debian:12
COPY --from=builder /app/main /output/main-glibc

VOLUME [ "/output" ]

CMD ["echo", "Binaire compilé avec glibc disponible dans /output/main"]
